---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(plotly)
library(p8105.datasets)

data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  rename(latitude = lat,longitude = long,borough=neighbourhood_group) %>%
  select(
    borough, neighbourhood, rating, price, room_type,
    latitude, longitude) %>%
  filter(!is.na(rating))
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boroughs = nyc_airbnb %>% distinct(borough) %>% pull()
room_types=nyc_airbnb %>% distinct(room_type) %>% pull()

selectInput(
  inputId = "borough_choice",
  label="Borough Choice",
  choices=boroughs
)

sliderInput(
  inputId = "price_range",
  label = h3("Price Range"),
  min = 50, max = 1000, value = c(100, 250)
)

radioButtons(
  inputId = "room_choice",
  label = h3("Room Type"),
  choices = room_types, selected = "Entire home/apt"
)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  nyc_airbnb %>%
  filter(
    borough == input$borough_choice,
    price %in% input$price_range[1]:input$price_range[2],
    room_type == input$room_choice) %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(
    x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
    alpha = 0.5, color = ~price, text = ~text_label)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
renderPlotly({
  nyc_airbnb %>% 
    filter(
      borough == input$borough_choice, 
      price %in% input$price_range[1]:input$price_range[2],
      room_type == input$room_choice) %>%
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
    plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
})
```

### Chart C

```{r}

```

